pow(a,b)

pow(a,b,m)

divmod(a,b)


In [1]:
print(divmod(177,10))

(17, 7)


In [2]:
import cmath # cmath.phase provide phase angle of a complex number

In [7]:
z=complex(input()) ##'complex()' is used to convert the input in a complex number
print(type(z))

1+2j
<class 'complex'>


In [3]:
print(cmath.phase(complex(-1.0,0.0))) ##'cmath.phase' will provide the phase angle for complex number 'z' check the o/p
print()

3.141592653589793


In [8]:
print(abs(complex(-1.0,0.0))) ## 'abs' give the ('r'=sqrt(x^2+y^2)) value of a complex number

1.0


In [16]:
for i in range(1,int(input())+1):
    print(((10**i-1)//9)**2)
    

4
1
121
12321
1234321


In [13]:
for i in range(3):
    print(i)
    print(i,i+1,i)



0
0 1 0
1
1 2 1
2
2 3 2


### Arrays

A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type

         import numpy

a = numpy.array([1,2,3,4,5])
print a[1]          #2

b = numpy.array([1,2,3,4,5],float)
print b[1]          #2.0

In [16]:
import numpy as np
lst=list(map(int,input().split()))
new_lst=[]
# lst
lst.reverse()
for i in lst:
    new_lst.append(i)
print(np.array(new_lst))   
    

1 2 3 4
[4 3 2 1]


In [18]:
ls=[1,2,3,4]
arr=np.array(ls)
print(arr)

[1 2 3 4]


## 'Shape' AND 'reshape'

In [21]:
arr1=np.array([1,2,3,4,5,6])
arr1.shape=(3,2)
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2=np.reshape(arr1,(6,1))  ## 'reshape' does not change the original data of an array.
print("new array : \n ",arr2)
print("original array : \n",arr1)

new array : 
  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
original array : 
 [[1 2]
 [3 4]
 [5 6]]


In [28]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

### 'transpose' and 'flatten'

In [57]:
arr1=np.array([[1,2,3,],[4,5,6]])
print("original array \n ",arr1,'\n','shape : ',arr1.shape)

print("transpose array \n ",arr1.transpose(),'shape new array :',(arr1.transpose().shape))
print('original array \n : ',arr1) #original array will remain same after

original array 
  [[1 2 3]
 [4 5 6]] 
 shape :  (2, 3)
transpose array 
  [[1 4]
 [2 5]
 [3 6]] shape new array : (3, 2)
original array 
 :  [[1 2 3]
 [4 5 6]]


### flatten

In [63]:
print("original array :\n ",arr1)
print('\n')
print("flattened array :",arr1.flatten())
print("original array :\n ",arr1)


original array :
  [[1 2 3]
 [4 5 6]]


flattened array : [1 2 3 4 5 6]
original array :
  [[1 2 3]
 [4 5 6]]


In [94]:
# n,m=map(int,input().split())
# for i in range(n):
arr=np.array([input().strip().split() for _ in range(3)],int)
arr

1 2 3
4 5 6
7 8 9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
import numpy
n,m,p=map(int,input().strip().split())
arr1=numpy.array([input().strip().split() for _ in range(n)],int)
arr2=numpy.array([input().strip().split() for _ in range(m)],int)
print(numpy.concatenate((aa1,arr2),axis=0))

4 3 2
1 2
3 4
4 5
5 6
6 2
3 4
5 6


NameError: name 'rr1' is not defined

In [2]:
import numpy as np
n,m,p=map(int,input().strip().split())
arr1=np.ones([_ for _ in range(n)])
arr2=np.zeros([_ for _ in range(m)])
print(arr1,arr2)
# n,mnumpy.ones([3,3,3])

3 3 3
[] []


In [108]:
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [126]:
# n,m,p=list(map(int,input().strip().split()))
# lst=[]
# lst.append(n)
# lst.append(m)
# lst.append(p)
# lst
print(np.ones([input().strip().split()]))
print(np.zeros([input().strip().split()]))

1 2 3


TypeError: 'list' object cannot be interpreted as an integer

In [125]:
[input().strip().split()]

1 2 3


[int, ['1', '2', '3']]

In [6]:
import numpy
numpy.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
shape=tuple(map(int,input().split()))
shape
print(nump)
numpy.ones(shape,dtype=int)

3 3 3


array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [18]:
# a=(2,3)
# np.eye(a)

n,m=map(int,input().split())
p=n
l=m


2 3
<class 'int'>


In [21]:
a,b=2,3
a%b

2

In [44]:
import numpy as np 
n,m=map(int,input().split())
A,B=np.array(tuple([input().split() for _ in range(n)]),int),np.array(tuple([input().split() for _ in range(n)]),int)
print(A,B)
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.floor_divide(A,B))
print(A%B)
print(A**B)

1 3
1 2 3
4 5 6
[[1 2 3]] [[4 5 6]]
[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[0 0 0]]
[[1 2 3]]
[[  1  32 729]]


In [25]:
np.array(tuple(map(int,input().split())))

2 3 4


array([2, 3, 4])

In [52]:
np.set_printoptions(legacy='1.13')

A=np.array(input().split(),float)
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1 2 3 4
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]


In [56]:
import numpy
n,m=map(int,input().split())
A=numpy.array([input().split() for _ in range(n)],int)
# A
print(numpy.sum(A,axis=0))
print(numpy.prod(A))


2 2
1 2
3 4
[4 6]
24


### functions 'mean', 'var', 'std' application on numpy array 

In [13]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8)],int)
print(a)
print("mean : ",np.mean(a,axis=0))
print("var : ",np.var(a,axis=0))
print("std : {:.11f}".format(np.std(a)))

[[1 2 3 4]
 [5 6 7 8]]
mean :  [3. 4. 5. 6.]
var :  [4. 4. 4. 4.]
std : 2.29128784748


#### 'poly','roots','polyint','polyder','polyval','polyfit' functions on numpy array

In [15]:
import numpy
arr=numpy.array([1,2,3])  ## this will be the polynomial from this array x^2+2x+3 ,value of this polynomial has been calculated at x=2 ,check o/p
print(numpy.polyval(arr,2))

11


In [5]:
import numpy
p=numpy.array(input().split(),float)
# p
x=float(input())
print(numpy.polyval(p,x))

1.1 2 3
0
3.0


In [17]:
a=[(1,2,3),(4,5,6),(7,8,9)]


for i in a:
    
    for j in i:
        print(j)
#     for j in i:
#         a=j
#         a=a+j
#     print(a)   
    

1
2
3
4
5
6
7
8
9


In [12]:
a=(1,2,3)
for i in a:
    a=i
    a=i+a
print(a)

6


In [79]:
import numpy as np
n,x=map(int,input().split())
lst=[]
for i in range(x):
    lst.append(map(float,input().split()))
   


2 2
1 2
3 4


[<map at 0xb81fd4bb48>, <map at 0xb8279c91c8>]

In [76]:
A=[1,2,3,4]
B=[3,4,5,6]
C=[2,3,4,5]
x=[A]+[B]+[C]

print(*x)
print(A)

[1, 2, 3, 4] [3, 4, 5, 6] [2, 3, 4, 5]
[1, 2, 3, 4]


In [56]:
print(zip([(1,2,3),(4,5,6)]))

In [67]:
print (list(zip([1,2,3,4,5,6],'Hacker')))

[(1, 'H'), (2, 'a'), (3, 'c'), (4, 'k'), (5, 'e'), (6, 'r')]


In [65]:
a,b=('chandan','pathak'),('hello','hi')
p=(zip(a,b))
print(tuple(p))
# a+b

(('chandan', 'hello'), ('pathak', 'hi'))


In [87]:
# first Method

lst=[1,2,3,4]
sqr=[]
for num in lst:
    sqr.append(num**2)
print('sqr list : ',sqr)

# Second Method:  
#  Advantages of using 'map' function
#  1.map is written in 'C' and highly optimized its internal empolied loop can be 
#    more efficient thaan a regular python for loop
#  2.Related memory consumption:-- with a for loop u need to store whole list in ur system memory ,
#    with map u get items on demand and only one item in our system memory at a given time.
#  3.In python 2.x,map() returns a list .This behaviour  changed in python 3.x
#    Now map() return a map object,which is an iterator that yields items on demand ,that's why we need to call a list 
#    to create the desired list object
def square(num):
    return num**2

A=map(square,[1,2,3,4])
print('A : ',list(A))

#Third Method:

B=map(lambda num :num**2,[1,2,3,4])
print('B : ',list(B))

sqr list :  [1, 4, 9, 16]
A :  [1, 4, 9, 16]
B :  [1, 4, 9, 16]
